MeLMSens_SteadyAdapt.exportBackgroundSplatterToCSV();
MeLMSens_SteadyAdapt.exportFlickerSplatterToCSV();
MeLMSens_SteadyAdapt.exportThresholdSplatterToCSV();
MeLMSens_Pulse.exportBackgroundSplatterToCSV();
MeLMSens_Pulse.exportFlickerSplatterToCSV();
MeLMSens_Pulse.exportThresholdSplatterToCSV();
MeLMSens_Pulse2.exportBackgroundSplatterToCSV();
MeLMSens_Pulse2.exportFlickerSplatterToCSV();