```{r setup}
library(tidyverse)
library(here)
source(here('R','clean_data.R'))
source(here('R','analyze_results.R'))
source(here('R','normalize_JNDs.R'))
source(here('R','results.plot.R'))
```
```{r load}
thresholds_splatter <- read_csv(here('data','experimental','adapt.thresholds.splatter.csv'))
```
```{r clean}
thresholds_splatter <- thresholds_splatter %>%
  rename_participants() %>%
  group_by(participant, session, axis, level) %>%
  mutate(contrastNominal= contrastNominalFit) %>%
  select(LMSBackgroundMeasured,contrastNominal)
```
```{r predict contrast}
JNDs <- thresholds_splatter %>%
    # Convert to wide-format: separate columns for high/low
    select(contrastNominal) %>%
    spread(key = level, value = contrastNominal) %>%
    
    # Calculate contrast predicted:
    # Equate for contrast nominal
    mutate(high = low) %>%
    gather(low,high,key='level',value='LMScontrastPredicted') %>%
    mutate(level=factor(level,levels=c('low','high'))) %>%
    right_join(thresholds_splatter) %>%
    
    # Calculate JND
    mutate(threshold_JND = LMScontrastPredicted * LMSBackgroundMeasured)
```
```{r}
JNDs <- normalize_JNDs(JNDs)
```
```{r}
medianJNDs <- median_JNDs(JNDs)
```
```{r}
plot_JNDs(JNDs,medianJNDs) +
    ylab("Predicted threshold (LMS JND, normalized") +
    ggtitle("Predicted threshold, if background LMS splatter is considered")
```